### ISSUE TITLE
Typescript v5.0でのコンフィグ`extends`の複数指定対応に合わせて、`tsconfig.json`を修正する

### ISSUE THREAD

**Issue by ReoHakase** [astronomy-club-at-nitic/nitic-astronomy#109]
複数からの継承が可能になったことを受けて幾つかのプリセットがdeprecatedになったので、新しい書き方に修正する。
e.g. https://www.npmjs.com/package/@tsconfig/next-strictest

> To give some more flexibility here, Typescript 5.0 now allows the extends field to take multiple entries. For example, in this configuration file:
```
{
    "extends": ["a", "b", "c"],
    "compilerOptions": {
        // ...
    }
}
```
> Writing this is kind of like extending c directly, where c extends b, and b extends a. If any fields "conflict", the latter entry wins.
> https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends

```
Progress: resolved 0, reused 1, downlpackages/tsconfig                        |  WARN  deprecated @tsconfig/node-lts-strictest@18.12.1
Progress: resolved 0, reused 1, downlpackages/tsconfig                        |  WARN  deprecated @tsconfig/node-lts-strictest-esm@18.12.1
Progress: resolved 0, reused 1, downlpackages/tsconfig                        |  WARN  deprecated @tsconfig/next-strictest@1.0.1
Progress: resolved 0, reused 1, downlProgress: resolved 22, reused 21, dowProgress: resolved 90, reused 83, dowProgress: resolved 167, reused 161, dProgress: resolved 222, reused 215, dProgress: resolved 247, reused 240, dProgress: resolved 326, reused 319, dProgress: resolved 414, reused 408, dProgress: resolved 498, reused 492, dProgress: resolved 511, reused 505, d.                                        |   +1
Progress: resolved 511, reused 505, dProgress: resolved 511, reused 505, downloaded 1, added 1, done
. prepare$ husky install
│ husky - Git hooks installed
└─ Done in 361ms
Done in 4.7s
```

**Comment by dino3616** [comment]
closed の理由はこれ？
- https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/67

**Comment by ReoHakase** [comment]
> closed の理由はこれ？
> 
> - https://github.com/astronomy-club-at-nitic/nitic-astronomy/pull/67

nextは確かlintもbuildも通った
イシューを閉じたのは、sb:buildが謎のタイプエラーで落ちるから

**Comment by dino3616** [comment]
なるほど？？
これだけだと他の人がよしなに次の行動に移せないので、close するときはもうちょい情報載っけてくれるとありがたみー 🙏 (自戒
