### ISSUE TITLE
OG画像を動的生成できるようにする

### ISSUE THREAD

**Issue by ReoHakase** [astronomy-club-at-nitic/nitic-astronomy#112]

**Comment by ReoHakase** [comment]
https://github.com/vercel/next.js/issues/48704#issue-1679300973

**Comment by dino3616** [comment]
調査あぁっす！

- Pro Plan でも ¥3000 /月 は愚かすぎる出費よなぁー (予算の8割てマ。。)
- まー別に OG なくてもコンテンツは見れるし。。 (アクセスは絶対減るけど。。)

と思ったので、 #112 くんはバックログ的優先度でいいんじゃないかなーと思いました
