### ISSUE TITLE
仮のルーティングを作成する

### ISSUE THREAD

**Issue by ReoHakase** [astronomy-club-at-nitic/nitic-astronomy#97]
# 概要
- Typed Routesを有効化したい [Statically Typed Links](https://nextjs.org/blog/next-13-2#statically-typed-links)
- ヘッダーを作成するときに参照先のリンクが存在しないと困るから、仮のものを作っておきたい
## 作りたいルートたち
- `/`
- `/article`
  - `/article/[articleId]`
- `/tag`
  - `/tag/[tagId]`
- `/member`
- `/not-found`
## 作りたい特殊ファイルたち
> https://beta.nextjs.org/docs/routing/fundamentals#file-conventions
![image](https://user-images.githubusercontent.com/16751535/232682254-a69b2eec-e58a-431d-add2-fda58880a701.png)

- `/not-found.tsx`

**Comment by dino3616** [comment]
Typed Routesを有効化するときに https://github.com/vercel/next.js/discussions/39942 とかでめっちゃ悲しくなったおもひで
もしかしたらもう改善されてるかもだけど一応補足だけ
